In [3]:
#FootBallGameData
#Instructions for this dataset:
# Simply copy ALL the lines in this script by pressing 
# CTRL+A on Windows 
# Once you have executed the commands the following objects
# will be created:
# Matrices:
# - Salary
# - Games
# - MinutesPlayed
# - FieldGoals
# - FieldGoalAttempts
# - Points
# Lists:
# - Players
# - Seasons
# Dictionaries:
# - Sdict
# - Pdict

#Comments:
#Seasons are labeled based on the first year in the season
#E.g. the 2012-2013 season is preseneted as simply 2012


#Import numpy
import numpy as np

#Seasons
Seasons = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
Sdict = {"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}

#Players
Players = ["David","Joe","James","Anthony","Danny","Chris","Paul","Kevin","Derrick","Dwayne"]
Pdict = {"David":0,"Joe":1,"James":2,"Anthony":3,"Danny":4,"Chris":5,"Paul":6,"Kevin":7,"Derrick":8,"Dwayne":9}

#Salaries
David_Salary = [15946875,17718750,19490625,21262500,23034375,24806250,25244493,27849149,30453805,23500000]
Joe_Salary = [12000000,12744189,13488377,14232567,14976754,16324500,18038573,19752645,21466718,23180790]
James_Salary = [4621800,5828090,13041250,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
Anthony_Salary = [3713640,4694041,13041250,14410581,15779912,17149243,18518574,19450000,22407474,22458000]
Danny_Salary = [4493160,4806720,6061274,13758000,15202590,16647180,18091770,19536360,20513178,21436271]
Chris_Salary = [3348000,4235220,12455000,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
Paul_Salary = [3144240,3380160,3615960,4574189,13520500,14940153,16359805,17779458,18668431,20068563]
Kevin_Salary = [0,0,4171200,4484040,4796880,6053663,15506632,16669630,17832627,18995624]
Derrick_Salary = [0,0,0,4822800,5184480,5546160,6993708,16402500,17632688,18862875]
Dwayne_Salary = [3031920,3841443,13041250,14410581,15779912,14200000,15691000,17182000,18673000,15000000]
#Matrix
Salary = np.array([David_Salary, Joe_Salary, James_Salary, Anthony_Salary, Danny_Salary, Chris_Salary, Paul_Salary, Kevin_Salary, Derrick_Salary, Dwayne_Salary])

#Games 
David_G = [80,77,82,82,73,82,58,78,6,35]
Joe_G = [82,57,82,79,76,72,60,72,79,80]
James_G = [79,78,75,81,76,79,62,76,77,69]
Anthony_G = [80,65,77,66,69,77,55,67,77,40]
Danny_G = [82,82,82,79,82,78,54,76,71,41]
Chris_G = [70,69,67,77,70,77,57,74,79,44]
Paul_G = [78,64,80,78,45,80,60,70,62,82]
Kevin_G = [35,35,80,74,82,78,66,81,81,27]
Derrick_G = [40,40,40,81,78,81,39,0,10,51]
Dwayne_G = [75,51,51,79,77,76,49,69,54,62]
#Matrix
Games = np.array([David_G, Joe_G, James_G, Anthony_G, Danny_G, Chris_G, Paul_G, Kevin_G, Derrick_G, Dwayne_G])

#Minutes Played
David_MP = [3277,3140,3192,2960,2835,2779,2232,3013,177,1207]
Joe_MP = [3340,2359,3343,3124,2886,2554,2127,2642,2575,2791]
James_MP = [3361,3190,3027,3054,2966,3063,2326,2877,2902,2493]
Anthony_MP = [2941,2486,2806,2277,2634,2751,1876,2482,2982,1428]
Danny_MP = [3021,3023,3088,2821,2843,2935,2070,2722,2396,1223]
Chris_MP = [2751,2658,2425,2928,2526,2795,2007,2454,2531,1556]
Paul_MP = [2808,2353,3006,3002,1712,2880,2181,2335,2171,2857]
Kevin_MP = [1255,1255,2768,2885,3239,3038,2546,3119,3122,913]
Derrick_MP = [1168,1168,1168,3000,2871,3026,1375,0,311,1530]
Dwayne_MP = [2892,1931,1954,3048,2792,2823,1625,2391,1775,1971]
#Matrix
MinutesPlayed = np.array([David_MP, Joe_MP, James_MP, Anthony_MP, Danny_MP, Chris_MP, Paul_MP, Kevin_MP, Derrick_MP, Dwayne_MP])

#Field Goals
David_FG = [978,813,775,800,716,740,574,738,31,266]
Joe_FG = [632,536,647,620,635,514,423,445,462,446]
James_FG = [875,772,794,789,768,758,621,765,767,624]
Anthony_FG = [756,691,728,535,688,684,441,669,743,358]
Danny_FG = [468,526,583,560,510,619,416,470,473,251]
Chris_FG = [549,543,507,615,600,524,393,485,492,343]
Paul_FG = [407,381,630,631,314,430,425,412,406,568]
Kevin_FG = [306,306,587,661,794,711,643,731,849,238]
Derrick_FG = [208,208,208,574,672,711,302,0,58,338]
Dwayne_FG = [699,472,439,854,719,692,416,569,415,509]
#Matrix
FieldGoals  = np.array([David_FG, Joe_FG, James_FG, Anthony_FG, Danny_FG, Chris_FG, Paul_FG, Kevin_FG, Derrick_FG, Dwayne_FG])

#Field Goal Attempts
David_FGA = [2173,1757,1690,1712,1569,1639,1336,1595,73,713]
Joe_FGA = [1395,1139,1497,1420,1386,1161,931,1052,1018,1025]
James_FGA = [1823,1621,1642,1613,1528,1485,1169,1354,1353,1279]
Anthony_FGA = [1572,1453,1481,1207,1502,1503,1025,1489,1643,806]
Danny_FGA = [881,873,974,979,834,1044,726,813,800,423]
Chris_FGA = [1087,1094,1027,1263,1158,1056,807,907,953,745]
Paul_FGA = [947,871,1291,1255,637,928,890,856,870,1170]
Kevin_FGA = [647,647,1366,1390,1668,1538,1297,1433,1688,467]
Derrick_FGA = [436,436,436,1208,1373,1597,695,0,164,835]
Dwayne_FGA = [1413,962,937,1739,1511,1384,837,1093,761,1084]
#Matrix
FieldGoalAttempts = np.array([David_FGA, Joe_FGA, James_FGA, Anthony_FGA, Danny_FGA, Chris_FGA, Paul_FGA, Kevin_FGA, Derrick_FGA, Dwayne_FGA])

#Points
David_PTS = [2832,2430,2323,2201,1970,2078,1616,2133,83,782]
Joe_PTS = [1653,1426,1779,1688,1619,1312,1129,1170,1245,1154]
James_PTS = [2478,2132,2250,2304,2258,2111,1683,2036,2089,1743]
Anthony_PTS = [2122,1881,1978,1504,1943,1970,1245,1920,2112,966]
Danny_PTS = [1292,1443,1695,1624,1503,1784,1113,1296,1297,646]
Chris_PTS = [1572,1561,1496,1746,1678,1438,1025,1232,1281,928]
Paul_PTS = [1258,1104,1684,1781,841,1268,1189,1186,1185,1564]
Kevin_PTS = [903,903,1624,1871,2472,2161,1850,2280,2593,686]
Derrick_PTS = [597,597,597,1361,1619,2026,852,0,159,904]
Dwayne_PTS = [2040,1397,1254,2386,2045,1941,1082,1463,1028,1331]
#Matrix
Points = np.array([David_PTS, Joe_PTS, James_PTS, Anthony_PTS, Danny_PTS, Chris_PTS, Paul_PTS, Kevin_PTS, Derrick_PTS, Dwayne_PTS])             
                  

In [9]:
import warnings
warnings.filterwarnings('ignore')
goalsPerGame = np.matrix.round(FieldGoals/Games)
print(goalsPerGame)


numpy.ndarray

In [11]:
goalsPerGame[Pdict["LeBronJames"]][Sdict["2012"]]

10.0

In [13]:
minutesPerGame = np.matrix.round(MinutesPlayed/Games)
print(minutesPerGame)

[[41. 41. 39. 36. 39. 34. 38. 39. 30. 34.]
 [41. 41. 41. 40. 38. 35. 35. 37. 33. 35.]
 [43. 41. 40. 38. 39. 39. 38. 38. 38. 36.]
 [37. 38. 36. 34. 38. 36. 34. 37. 39. 36.]
 [37. 37. 38. 36. 35. 38. 38. 36. 34. 30.]
 [39. 39. 36. 38. 36. 36. 35. 33. 32. 35.]
 [36. 37. 38. 38. 38. 36. 36. 33. 35. 35.]
 [36. 36. 35. 39. 40. 39. 39. 39. 39. 34.]
 [29. 29. 29. 37. 37. 37. 35. nan 31. 30.]
 [39. 38. 38. 39. 36. 37. 33. 35. 33. 32.]]


In [20]:
goalAccuray = np.matrix.round(FieldGoals/FieldGoalAttempts*100)
print(goalAccuray)


[[45. 46. 46. 47. 46. 45. 43. 46. 42. 37.]
 [45. 47. 43. 44. 46. 44. 45. 42. 45. 44.]
 [48. 48. 48. 49. 50. 51. 53. 56. 57. 49.]
 [48. 48. 49. 44. 46. 46. 43. 45. 45. 44.]
 [53. 60. 60. 57. 61. 59. 57. 58. 59. 59.]
 [51. 50. 49. 49. 52. 50. 49. 53. 52. 46.]
 [43. 44. 49. 50. 49. 46. 48. 48. 47. 49.]
 [47. 47. 43. 48. 48. 46. 50. 51. 50. 51.]
 [48. 48. 48. 48. 49. 45. 43. nan 35. 40.]
 [49. 49. 47. 49. 48. 50. 50. 52. 55. 47.]]


In [27]:
goalAccuray = np.nan_to_num(goalAccuray)

In [31]:
print(goalAccuray.max())
print(goalAccuray.min())


61.0
0.0


In [29]:
goalAccuray

array([[45., 46., 46., 47., 46., 45., 43., 46., 42., 37.],
       [45., 47., 43., 44., 46., 44., 45., 42., 45., 44.],
       [48., 48., 48., 49., 50., 51., 53., 56., 57., 49.],
       [48., 48., 49., 44., 46., 46., 43., 45., 45., 44.],
       [53., 60., 60., 57., 61., 59., 57., 58., 59., 59.],
       [51., 50., 49., 49., 52., 50., 49., 53., 52., 46.],
       [43., 44., 49., 50., 49., 46., 48., 48., 47., 49.],
       [47., 47., 43., 48., 48., 46., 50., 51., 50., 51.],
       [48., 48., 48., 48., 49., 45., 43.,  0., 35., 40.],
       [49., 49., 47., 49., 48., 50., 50., 52., 55., 47.]])

In [89]:
# whose goal accuracy is maximum
# Python’s built-in enumerate function allows us to loop over a list and retrieve both the index and the value of each item in the list

for index, item in enumerate(goalAccuray):
     print(index,item)


0 [45. 46. 46. 47. 46. 45. 43. 46. 42. 37.]
1 [45. 47. 43. 44. 46. 44. 45. 42. 45. 44.]
2 [48. 48. 48. 49. 50. 51. 53. 56. 57. 49.]
3 [48. 48. 49. 44. 46. 46. 43. 45. 45. 44.]
4 [53. 60. 60. 57. 61. 59. 57. 58. 59. 59.]
5 [51. 50. 49. 49. 52. 50. 49. 53. 52. 46.]
6 [43. 44. 49. 50. 49. 46. 48. 48. 47. 49.]
7 [47. 47. 43. 48. 48. 46. 50. 51. 50. 51.]
8 [48. 48. 48. 48. 49. 45. 43.  0. 35. 40.]
9 [49. 49. 47. 49. 48. 50. 50. 52. 55. 47.]


In [91]:
# whose goal accuracy is maximum
for i in range(len(goalAccuray)):
    for j in range(len(goalAccuray)):
        if goalAccuray [i][j] == goalAccuray.max():
            print(i,j,goalAccuray [i][j])
            for p in Pdict:
                if Pdict[p] == i:
                    print(p)
            for s in Sdict:
                if Sdict[s] == j:
                    print(s)
        


4 4 61.0
DwightHoward
2009


In [92]:
# whose goal accuracy is minimum
for i in range(len(goalAccuray)):
    for j in range(len(goalAccuray)):
        if goalAccuray [i][j] == goalAccuray.min():
            print(i,j,goalAccuray [i][j])
            for p in Pdict:
                if Pdict[p] == i:
                    print(p)
            for s in Sdict:
                if Sdict[s] == j:
                    print(s)


8 7 0.0
DerrickRose
2012


In [99]:
list1 = np.arange(0,20)

In [100]:
list1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [101]:
m1 = np.reshape(list1,(5,4))

In [102]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [103]:
m2 = np.reshape(list1,(5,4),order = 'F')

In [104]:
m2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [105]:
m1+m2

array([[ 0,  6, 12, 18],
       [ 5, 11, 17, 23],
       [10, 16, 22, 28],
       [15, 21, 27, 33],
       [20, 26, 32, 38]])

In [106]:
m1-m2

array([[  0,  -4,  -8, -12],
       [  3,  -1,  -5,  -9],
       [  6,   2,  -2,  -6],
       [  9,   5,   1,  -3],
       [ 12,   8,   4,   0]])

In [107]:
m1*m2

array([[  0,   5,  20,  45],
       [  4,  30,  66, 112],
       [ 16,  63, 120, 187],
       [ 36, 104, 182, 270],
       [ 64, 153, 252, 361]])

In [108]:
m1/m2

array([[       nan, 0.2       , 0.2       , 0.2       ],
       [4.        , 0.83333333, 0.54545455, 0.4375    ],
       [4.        , 1.28571429, 0.83333333, 0.64705882],
       [4.        , 1.625     , 1.07692308, 0.83333333],
       [4.        , 1.88888889, 1.28571429, 1.        ]])

In [109]:
np.nan_to_num(m1/m2)

array([[0.        , 0.2       , 0.2       , 0.2       ],
       [4.        , 0.83333333, 0.54545455, 0.4375    ],
       [4.        , 1.28571429, 0.83333333, 0.64705882],
       [4.        , 1.625     , 1.07692308, 0.83333333],
       [4.        , 1.88888889, 1.28571429, 1.        ]])